### ISSUE TITLE
Inquiry Regarding Validity of UI Screen Elements in Dataset

### ISSUE THREAD

**Issue by BorisYang326** [google-research-datasets/clay#3]
Hi!
First of all, I want to express my gratitude for the incredible work you all have done on this project. It's truly impressive!
I noticed in the paper that it mentions: “_After labeling the entire dataset that consists of 59,555 UI screens, 22,273 screens or 37.4% of the dataset contain at least one invalid element._”
From my understanding, it seems we can filter out samples containing the "**INVALID**" label to obtain the remaining 62.6% of valid samples. However, I couldn't find this label in the CSV file provided.
Could you please clarify how we can determine whether an element is valid or invalid?
Thank you for your help!

**Comment by leebird** [comment]
Hi, IIRC BACKGROUND is the invalid label. Thanks!

**Comment by BorisYang326** [comment]
Got it, thanks for clarifying! That makes sense now. Appreciate your help!
