### ISSUE TITLE
Questions about the Logic in "Occluded boxes are cut of to include only the visible part"

### ISSUE THREAD

**Issue by Rykertang** [google-research-datasets/clay#4]
Hello, I think this work is of great value. Thank your team very much for your contribution.
However, I have some questions regarding the specific details and would like to consult you.
Regarding the sentence "Occluded boxes are cut of to include only the visible part" in the article, could you please tell me the detailed logic?
My questions are as follows:
How to judge overlapping objects?
My assumed answer: Firstly, they need to be at the same level (under the same parent node). Secondly, there should be overlaps both in the horizontal and vertical directions.
How to handle overlapping objects?
Which object should the overlapping part be assigned to?

**Comment by leebird** [comment]
I believed we depended on the pre-order traversal of the view hierarchy tree to decide if an object is occluded by another object: https://developer.android.com/guide/topics/ui/how-android-draws. Please see more details in Section 3.1 on page 4 of the paper. Thanks!

**Comment by Rykertang** [comment]
Thanks for your answer!
